name: Terraform CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.3

    - name: Initialize Terraform
      working-directory: infra
      run: terraform init

    - name: Validate Terraform
      working-directory: infra
      run: terraform validate

    - name: Plan Terraform
      working-directory: infra
      id: planning
      run: terraform plan -out=tfplan
      continue-on-error: true

    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}
        terraform_plan_path: infra/tfplan

    - name: Generate Infracost cost estimate baseline
      run: |
        infracost breakdown --path=./infra \
                            --format=json \
                            --out-file=/tmp/infracost-base.json
  
    - name: Generate Infracost diff
      run: |
        infracost diff --path=./infra \
                        --format=json \
                        --compare-to=/tmp/infracost-base.json \
                        --out-file=/tmp/infracost.json

    - name: Post Infracost comment
      run: |
          infracost comment github --path=/tmp/infracost.json \
                                    --repo=$GITHUB_REPOSITORY \
                                    --github-token=${{github.token}} \
                                    --pull-request=${{github.event.pull_request.number}} \
                                    --behavior=update

    - name: Apply Terraform
      if: success() && github.event_name == 'push'
      working-directory: infra
      run: terraform destroy tfplan
      env:
        TF_CLI_AUTO_APPROVE: 1